# Generated by Django 5.0 on 2023-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('Division_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Division_name', models.CharField(max_length=30)),
                ('Street_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('Post_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=30)),
                ('Salary', models.IntegerField(default=14375)),
            ],
        ),
    ]
