# Generated by Django 5.0 on 2023-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('Client_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Phone_number', models.BigIntegerField()),
                ('Passport_series', models.IntegerField()),
                ('Passport_number', models.IntegerField()),
            ],
        ),
    ]
