# Generated by Django 5.0 on 2023-12-09 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Phone_number', models.BigIntegerField()),
                ('Division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.divisions')),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.posts')),
            ],
        ),
    ]
