# Generated by Django 5.0 on 2023-12-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Category_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Refund_possibility', models.BooleanField()),
                ('Division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.divisions')),
            ],
        ),
        migrations.CreateModel(
            name='Pledged_items_list',
            fields=[
                ('Pledged_items_list_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Pledged_item_name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Quality', models.IntegerField()),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('Contract_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Sign_date', models.DateTimeField()),
                ('Expiration_date', models.DateTimeField()),
                ('Bail', models.IntegerField()),
                ('Commision_fee', models.IntegerField()),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.clients')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.employees')),
                ('Pledged_items_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.pledged_items_list')),
            ],
        ),
    ]
